name: CI/CD - Build, Push, and Deploy

on:
  push:
    branches: [main]

jobs:
  build_push_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push auth-service image
        uses: docker/build-push-action@v4
        with:
          context: ./auth-service
          file: ./auth-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest

      - name: Build and push vehicle-service image
        uses: docker/build-push-action@v4
        with:
          context: ./vehicle-service
          file: ./vehicle-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vehicle-service:latest

      - name: Deploy to EC2 Instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            # Navega até a pasta do projeto no servidor
            cd /home/ubuntu/revenda-veiculos

            # Puxa as imagens mais recentes do Docker Hub
            docker compose pull

            # Reinicia os serviços com as novas imagens
            docker compose up -d

            # Limpa imagens antigas não utilizadas
            docker image prune -f
