name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: . # Assumindo que o workflow está na raiz do microsserviço
          file: ./Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }} # Só faz push se for merge na main
          tags: seu-usuario-docker/auth-service:latest # Mude o nome da imagem


    # Aqui viria o passo de deploy, que depende da sua infraestrutura
    # Ex: SSH para um servidor e rodar 'docker-compose pull && docker-compose up -d'
    # - name: Deploy to production
    #   if: github.ref == 'refs/heads/main'
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     key: ${{ secrets.PRIVATE_KEY }}
    #     script: |
    #       cd /caminho/para/seu/docker-compose
    #       docker-compose pull auth-service # Puxa a nova imagem
    #       docker-compose up -d --no-deps auth-service # Reinicia o serviço
